spring.application.name=mascotas
server.port=8081

# --- CONEXIÓN DIRECTA A AIVEN DESDE LOCALHOST ---
spring.datasource.url=jdbc:mysql://practica3-federeip-7b8c.e.aivencloud.com:16113/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ayYXAuHzis53qVLuOAW

# --- CONFIGURACIÓN DE HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect